name: Python CI
on: 

  push:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: deluxepaintingservice

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Building web app
      uses: azure/appservice-build@v2
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: deluxepaintingservice
        publish-profile: <publishData><publishProfile profileName="deluxepaintingservice - Web Deploy" publishMethod="MSDeploy" publishUrl="deluxepaintingservice.scm.azurewebsites.net:443" msdeploySite="deluxepaintingservice" userName="$deluxepaintingservice" userPWD="2jvyrSkMWqvhGMYCvCmdGsecNinB0sPxBAnuaauLf4gZtpP9JPB2QjuWnXN9" destinationAppUrl="http://deluxepaintingservice.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="deluxepaintingservice - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-blu-249.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="deluxepaintingservice\$deluxepaintingservice" userPWD="2jvyrSkMWqvhGMYCvCmdGsecNinB0sPxBAnuaauLf4gZtpP9JPB2QjuWnXN9" destinationAppUrl="http://deluxepaintingservice.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="deluxepaintingservice - Zip Deploy" publishMethod="ZipDeploy" publishUrl="deluxepaintingservice.scm.azurewebsites.net:443" userName="$deluxepaintingservice" userPWD="2jvyrSkMWqvhGMYCvCmdGsecNinB0sPxBAnuaauLf4gZtpP9JPB2QjuWnXN9" destinationAppUrl="http://deluxepaintingservice.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>

