name: Python CI
on: 

  push:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: painting-website-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Building web app
      uses: azure/appservice-build@v2
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: painting-website-test
        publish-profile: <publishData><publishProfile profileName="painting-website-test - Web Deploy" publishMethod="MSDeploy" publishUrl="painting-website-test.scm.azurewebsites.net:443" msdeploySite="painting-website-test" userName="$painting-website-test" userPWD="6zxeaKxZaBX91LhJT3BufernphHlHWaRvE850qldG2f0zj7qACfqu7RbSYJ4" destinationAppUrl="http://painting-website-test.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="painting-website-test - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-blu-219.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="painting-website-test\$painting-website-test" userPWD="6zxeaKxZaBX91LhJT3BufernphHlHWaRvE850qldG2f0zj7qACfqu7RbSYJ4" destinationAppUrl="http://painting-website-test.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="painting-website-test - Zip Deploy" publishMethod="ZipDeploy" publishUrl="painting-website-test.scm.azurewebsites.net:443" userName="$painting-website-test" userPWD="6zxeaKxZaBX91LhJT3BufernphHlHWaRvE850qldG2f0zj7qACfqu7RbSYJ4" destinationAppUrl="http://painting-website-test.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>

