name: Deploy to production
on: 

  push:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: daluxepaintingservice

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Building web app
      uses: azure/appservice-build@v2
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: daluxepaintingservice
        publish-profile: <publishData><publishProfile profileName="daluxepaintingservice - Web Deploy" publishMethod="MSDeploy" publishUrl="daluxepaintingservice.scm.azurewebsites.net:443" msdeploySite="daluxepaintingservice" userName="$daluxepaintingservice" userPWD="GHFjskHa5nj33B0tkJsC41xWLaNJpw4Ndn01nseGJlpL3nxT8oAE20joZYtu" destinationAppUrl="http://daluxepaintingservice.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="daluxepaintingservice - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-blu-249.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="daluxepaintingservice\$daluxepaintingservice" userPWD="GHFjskHa5nj33B0tkJsC41xWLaNJpw4Ndn01nseGJlpL3nxT8oAE20joZYtu" destinationAppUrl="http://daluxepaintingservice.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="daluxepaintingservice - Zip Deploy" publishMethod="ZipDeploy" publishUrl="daluxepaintingservice.scm.azurewebsites.net:443" userName="$daluxepaintingservice" userPWD="GHFjskHa5nj33B0tkJsC41xWLaNJpw4Ndn01nseGJlpL3nxT8oAE20joZYtu" destinationAppUrl="http://daluxepaintingservice.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>

